line-length = 120

[lint]
preview = true
pydocstyle.convention = "google"
isort.split-on-trailing-comma = true
select = [
    "E301",
    "E305",
    "E306",
    "F401",
]

[format]
quote-style = "double"
indent-style = "space"
