dataset_params:
  im_train_path: 'VOC2007/JPEGImages'
  ann_train_path: 'VOC2007/Annotations'
  im_test_path: 'VOC2007-test/JPEGImages'
  ann_test_path: 'VOC2007-test/Annotations'
  num_classes : 21

model_params:
  im_size: 448
  num_anchors: 1
  grid_size: 14
  

train_params:
  task_name: 'voc'
  seed : 1111
  acc_steps : 1 # increase you want to get gradients from >1 steps(kind of mimicking >1 batch size)
  num_epochs: 20
  lr_steps : [12, 16]
  lr: 0.0001
  ckpt_name: 'yolo_voc2007.pth'
  batch_size: 32